language: node_js
notifications:
  email:
  - alvinxu@outlook.com
node_js:
  - 0.12
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"